[tool.poetry]
name = "practical01"
version = "0.1.0"
description = ""
authors = ["Aman Gupta <aman.gupta@uqconnect.edu.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
